spring:
  profiles:
    active: "smart"
    
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      
hr: 
  salary: 
    def:
      percent: 5
    smart:
      limits:
       1: 1
       2.5: 2
       5: 5
       10: 10
       7.5: 8