spring:
  profiles:
    active: "smart"

hr: 
  salary: 
    def:
      percent: 5
    smart:
      limit1: 10
      limit2: 5
      limit3: 2.5
      percent1: 10 
      percent2: 5
      percent3: 2